apiVersion: v1
kind: Pod
metadata:
  name: kaniko
spec:
  containers:
  - name: kaniko
    image: uhub.service.ucloud.cn/longlong/kaniko:v1.0
    #    image: uhub.service.ucloud.cn/ucloud/ubuntu-16.04-ssh:latest 
    args: [
    "--dockerfile=/workspace/Dockerfile",
    "--context=/workspace/",
    "--destination=uhub.service.ucloud.cn/longlong/ubuntu1:v1.0"] # replace with your dockerhub account
    volumeMounts:
      - name: kaniko-secret
        mountPath: /kaniko/.docker
      - name: dockerfile-storage
        mountPath: /workspace
  restartPolicy: Never
  volumes:
    - name: kaniko-secret
      secret:
        secretName: regcred
    - name: dockerfile-storage
      hostPath:
        path: /data/kaniko
        type: Directory
